In [3]:
#Importing the usual libraries.
import numpy as np
import tensorly as tl
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.io import loadmat

#Setting style options.
sns.set()
np.set_printoptions(1)

The following packages are used in this notebook:

- `numpy 1.18.1`
- `tensorly 0.4.3`
- `seaborn 0.10.0`

# Problem 1 - Unfolding

For a third-order tensor $\mathbf{\mathcal{X}} \in \mathbb{C}^{I \times J \times K}$ , using the concept of n-mode fibers, implement the function unfold according to the following prototype:

\begin{equation}
 [\mathbf{\mathcal{X}}]_{(n)} = unfold(\mathbf{\mathcal{X}},n) 
\end{equation}

Hint: Use the file “unfolding_folding.mat” to validate your function.

<font color='red'>Solution:</font>

In [4]:
def unfold(X,n):
    
    X = np.moveaxis(X,n,0)
    X = X.reshape(X.shape[0],-1)
    
    return X

In [3]:
X = np.moveaxis(np.arange(1,25).reshape([2,3,4]),1,2).reshape([2,3,4],order = 'F')
print(X)

[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]

 [[13 16 19 22]
  [14 17 20 23]
  [15 18 21 24]]]


In [711]:
print('Tensor X unfolding mode-1:')
print(unfold(X,1))
print('Tensor X unfolding mode-2:')
print(unfold(X,2))
print('Tensor X unfolding mode-3:')
print(unfold(X,0))

Tensor X unfolding mode-1:
[[ 1  4  7 10 13 16 19 22]
 [ 2  5  8 11 14 17 20 23]
 [ 3  6  9 12 15 18 21 24]]
Tensor X unfolding mode-2:
[[ 1  2  3 13 14 15]
 [ 4  5  6 16 17 18]
 [ 7  8  9 19 20 21]
 [10 11 12 22 23 24]]
Tensor X unfolding mode-3:
[[ 1  4  7 10  2  5  8 11  3  6  9 12]
 [13 16 19 22 14 17 20 23 15 18 21 24]]


# Test with unfolding_folding.mat

In [4]:
tenX = np.load('tenX.npy')
print('Tensor:')
print(tenX)

X1 = np.load('X1.npy')
print('X1:')
print(X1)

X2 = np.load('X2.npy')
print('X2:')
print(X2)

X3 = np.load('X3.npy')
print('X3:')
print(X3)

Tensor:
[[[ -1.8   3.8   2.3   1. ]
  [ -1.2   1.8   5.    3.6]
  [  3.2  -6.2  -7.1  -4.4]]

 [[ -0.7   1.7   0.   -0.3]
  [ -0.1   0.5  -1.2  -1.1]
  [  1.   -2.5   1.    1.3]]

 [[  1.4  -3.2  -1.   -0.1]
  [  0.6  -1.2  -1.1  -0.6]
  [ -2.3   4.9   2.1   0.7]]

 [[ -1.2   2.2   3.3   2.2]
  [ -1.5   1.6   9.9   7.6]
  [  2.7  -4.  -12.7  -9.3]]

 [[ -2.2   4.5   3.7   2. ]
  [ -1.8   2.5   9.6   7.1]
  [  4.3  -7.6 -12.9  -8.7]]]
X1:
[[ -1.8   3.8   2.3   1.   -0.7   1.7   0.   -0.3   1.4  -3.2  -1.   -0.1
   -1.2   2.2   3.3   2.2  -2.2   4.5   3.7   2. ]
 [ -1.2   1.8   5.    3.6  -0.1   0.5  -1.2  -1.1   0.6  -1.2  -1.1  -0.6
   -1.5   1.6   9.9   7.6  -1.8   2.5   9.6   7.1]
 [  3.2  -6.2  -7.1  -4.4   1.   -2.5   1.    1.3  -2.3   4.9   2.1   0.7
    2.7  -4.  -12.7  -9.3   4.3  -7.6 -12.9  -8.7]]
X2:
[[ -1.8  -1.2   3.2  -0.7  -0.1   1.    1.4   0.6  -2.3  -1.2  -1.5   2.7
   -2.2  -1.8   4.3]
 [  3.8   1.8  -6.2   1.7   0.5  -2.5  -3.2  -1.2   4.9   2.2   1.6  -4.
    4.5   

In [5]:
print('unfolding_folding.mat 1-mode:')
print(X1)
print('unfold function 1-mode:')
print(unfold(tenX,1))
print('unfolding_folding.mat 2-mode:')
print(X2)
print('unfold function 2-mode:')
print(unfold(tenX,2))
print('unfolding_folding.mat 3-mode:')
print(X3)
print('unfold function 3-mode:')
print(unfold(tenX,0))

unfolding_folding.mat 1-mode:
[[ -1.8   3.8   2.3   1.   -0.7   1.7   0.   -0.3   1.4  -3.2  -1.   -0.1
   -1.2   2.2   3.3   2.2  -2.2   4.5   3.7   2. ]
 [ -1.2   1.8   5.    3.6  -0.1   0.5  -1.2  -1.1   0.6  -1.2  -1.1  -0.6
   -1.5   1.6   9.9   7.6  -1.8   2.5   9.6   7.1]
 [  3.2  -6.2  -7.1  -4.4   1.   -2.5   1.    1.3  -2.3   4.9   2.1   0.7
    2.7  -4.  -12.7  -9.3   4.3  -7.6 -12.9  -8.7]]
unfold function 1-mode:
[[ -1.8   3.8   2.3   1.   -0.7   1.7   0.   -0.3   1.4  -3.2  -1.   -0.1
   -1.2   2.2   3.3   2.2  -2.2   4.5   3.7   2. ]
 [ -1.2   1.8   5.    3.6  -0.1   0.5  -1.2  -1.1   0.6  -1.2  -1.1  -0.6
   -1.5   1.6   9.9   7.6  -1.8   2.5   9.6   7.1]
 [  3.2  -6.2  -7.1  -4.4   1.   -2.5   1.    1.3  -2.3   4.9   2.1   0.7
    2.7  -4.  -12.7  -9.3   4.3  -7.6 -12.9  -8.7]]
unfolding_folding.mat 2-mode:
[[ -1.8  -1.2   3.2  -0.7  -0.1   1.    1.4   0.6  -2.3  -1.2  -1.5   2.7
   -2.2  -1.8   4.3]
 [  3.8   1.8  -6.2   1.7   0.5  -2.5  -3.2  -1.2   4.9   2.2   1.6  

# Problem 2 - Folding

Implement the function fold that converts the unfolding $[\mathbf{\mathcal{X}}]_{(n)}$ obtained with $unfold (\mathbf{\mathcal{X}}, n)$ back to the tensor $\mathbf{\mathcal{X}} \in \mathbb{C}^{I \times J \times K}$ (i.e., a 3-d array in Matlab/Octave), according to the following prototype:

\begin{equation}
 \mathbf{\mathcal{X}} = fold([\mathbf{\mathcal{X}}]_{(n)},[I,J,K],n) 
\end{equation}

Hint: Use the file “unfolding_folding.mat” to validate your function.

<font color='red'>Solution:</font>

In [5]:
def fold(Xn,X_shape,n):
    
    #Transforming the shape of tensor tuple into a list for easy manipulation.
    shape = list(X_shape)
    #Extracting the external dimension that is presented in the unfolding tensor as the number of rows.
    n_dimension = shape.pop(n)
    #Inserting the previously dimension at the begining of the shape vector so this way we have a dinamic reshape
    #that will change in accord with the unfolding mode.
    shape.insert(0, n_dimension)
    
    #Reorganizing the unfolded tensor as a tensor.
    X = Xn.reshape(shape)

    #Moving back the axis that was changed at the unfolding function.
    X = np.moveaxis(X,0,n)
    
    return X

In [7]:
X = np.moveaxis(np.arange(1,25).reshape([2,3,4]),1,2).reshape([2,3,4],order = 'F')
print(X)

[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]

 [[13 16 19 22]
  [14 17 20 23]
  [15 18 21 24]]]


In [8]:
n = 2
Xn = unfold(X,n)
print('Tensor X unfolding',n,'- mode')
print(Xn)

Tensor X unfolding 2 - mode
[[ 1  2  3 13 14 15]
 [ 4  5  6 16 17 18]
 [ 7  8  9 19 20 21]
 [10 11 12 22 23 24]]


In [9]:
Y = fold(Xn,X.shape,n)
print('Tensor X folding',n,'- mode')
print(Y)

Tensor X folding 2 - mode
[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]

 [[13 16 19 22]
  [14 17 20 23]
  [15 18 21 24]]]


# Test with unfolding_folding.mat

In [10]:
print('Tensor X:')
print(tenX)

Tensor X:
[[[ -1.8   3.8   2.3   1. ]
  [ -1.2   1.8   5.    3.6]
  [  3.2  -6.2  -7.1  -4.4]]

 [[ -0.7   1.7   0.   -0.3]
  [ -0.1   0.5  -1.2  -1.1]
  [  1.   -2.5   1.    1.3]]

 [[  1.4  -3.2  -1.   -0.1]
  [  0.6  -1.2  -1.1  -0.6]
  [ -2.3   4.9   2.1   0.7]]

 [[ -1.2   2.2   3.3   2.2]
  [ -1.5   1.6   9.9   7.6]
  [  2.7  -4.  -12.7  -9.3]]

 [[ -2.2   4.5   3.7   2. ]
  [ -1.8   2.5   9.6   7.1]
  [  4.3  -7.6 -12.9  -8.7]]]


In [11]:
print('Tensor X unfolding 1-mode:')
X1 = unfold(tenX,0)
print(X1)

Tensor X unfolding 1-mode:
[[ -1.8   3.8   2.3   1.   -1.2   1.8   5.    3.6   3.2  -6.2  -7.1  -4.4]
 [ -0.7   1.7   0.   -0.3  -0.1   0.5  -1.2  -1.1   1.   -2.5   1.    1.3]
 [  1.4  -3.2  -1.   -0.1   0.6  -1.2  -1.1  -0.6  -2.3   4.9   2.1   0.7]
 [ -1.2   2.2   3.3   2.2  -1.5   1.6   9.9   7.6   2.7  -4.  -12.7  -9.3]
 [ -2.2   4.5   3.7   2.   -1.8   2.5   9.6   7.1   4.3  -7.6 -12.9  -8.7]]


In [12]:
print('Folding of X1 according with 1-mode:')
print(fold(X1,tenX.shape,0))

Folding of X1 according with 1-mode:
[[[ -1.8   3.8   2.3   1. ]
  [ -1.2   1.8   5.    3.6]
  [  3.2  -6.2  -7.1  -4.4]]

 [[ -0.7   1.7   0.   -0.3]
  [ -0.1   0.5  -1.2  -1.1]
  [  1.   -2.5   1.    1.3]]

 [[  1.4  -3.2  -1.   -0.1]
  [  0.6  -1.2  -1.1  -0.6]
  [ -2.3   4.9   2.1   0.7]]

 [[ -1.2   2.2   3.3   2.2]
  [ -1.5   1.6   9.9   7.6]
  [  2.7  -4.  -12.7  -9.3]]

 [[ -2.2   4.5   3.7   2. ]
  [ -1.8   2.5   9.6   7.1]
  [  4.3  -7.6 -12.9  -8.7]]]


# Problem 3 - Tensor x Matrix Product

For given matrices $A \in \mathbb{C}^{P \times I}$, $B \in \mathbb{C}^{Q \times J}$ and $C \in \mathbb{C}^{R \times K}$ and tensor $\mathbf{\mathcal{X}} \in \mathbb{C}^{I \times J \times K}$ , calculate the tensor $\mathbf{\mathcal{Y}} \in \mathbb{C}^{P \times Q \times R}$ via the following multilinear transformation:

\begin{equation}
    \mathbf{\mathcal{Y}} = \mathbf{\mathcal{X}} \times_{1} \mathbf{A} \times_{2} \mathbf{B} \times_{3} \mathbf{C}
\end{equation}

Hint: Use the file “multilinear_product.mat” to validate your result.

<font color='red'>Solution:</font>

In [6]:
def ten_mat_prod(tensor,matrix,mode):
    
    shape = list(tensor.shape)
    shape.pop(mode)
    shape.insert(mode,matrix.shape[0])
    
    tensor = matrix@unfold(tensor,mode)
    tensor = fold(tensor,shape,mode)
    
    return tensor

In [7]:
def ten_mat_multiprod(tensor,list_of_matrices):
    
    shape = list(tensor.shape)
    
    for i in range(0,list_of_matrices.shape[0]):
        
        tensor = list_of_matrices[i,]@(unfold(tensor,i))
        Z = list_of_matrices[i]
        shape.pop(i)
        shape.insert(i,Z.shape[0])
        tensor = fold(tensor,shape,i)
        shape = list(tensor.shape)
        
    return tensor

In [15]:
A = np.random.randn(4,3) + 1j*np.random.randn(4,3)
B = np.random.randn(5,4) + 1j*np.random.randn(5,4)
C = np.random.randn(3,2) + 1j*np.random.randn(3,2)
D = np.array([A,B,C])
print(D.shape)
X = np.random.randn(3,4,2)

(3,)


In [16]:
ten_mat_multiprod(X,D)

array([[[-2.7e+00 +7.1j,  3.5e+00 -9.7j, -6.3e+00-10.2j],
        [-3.5e+00 -0.4j,  2.8e+00 -0.1j,  2.3e+00 -4.j ],
        [-9.1e-01 -6.5j,  2.3e+00+11.4j,  1.0e+01 +6.9j],
        [-6.1e+00 +4.5j,  5.1e+00 -0.3j, -8.0e-01 -6.8j],
        [ 1.2e+01-10.7j, -6.8e+00 +2.2j,  6.1e+00+13.6j]],

       [[-8.2e+00 -5.5j, -6.2e+00 -4.5j, -9.8e-01-10.2j],
        [-2.4e+00 -5.2j, -1.1e+00 +0.8j,  4.1e+00 -1.7j],
        [ 1.5e+01 +3.9j,  9.6e+00 -2.6j,  4.0e+00+10.1j],
        [-1.1e+01 -3.j , -2.3e+00+10.1j,  2.6e+00 -2.2j],
        [ 1.8e+01 -0.3j,  5.5e+00 -6.9j,  4.2e+00+10.3j]],

       [[-3.1e+00 -9.5j, -2.3e+00 -8.2j,  5.2e+00 -9.3j],
        [ 1.3e+00 -3.2j,  1.9e+00 -1.8j,  4.2e+00 -0.7j],
        [ 1.4e+01+10.j ,  4.0e+00 +2.1j, -5.1e+00+14.1j],
        [-1.3e+01 -4.2j,  2.5e+00 +8.j ,  6.7e+00 -7.1j],
        [ 1.7e+01+10.5j,  5.7e+00 -1.8j, -4.8e+00+14.2j]],

       [[-6.3e+00 -1.5j,  6.9e+00 +0.j ,  6.3e+00 -7.5j],
        [ 3.0e-04 -4.5j, -1.4e+00 +2.2j,  3.6e+00 +1.7j],
        

In [17]:
tl.tenalg.multi_mode_dot(X,[A,B,C])

array([[[-2.7e+00 +7.1j,  3.5e+00 -9.7j, -6.3e+00-10.2j],
        [-3.5e+00 -0.4j,  2.8e+00 -0.1j,  2.3e+00 -4.j ],
        [-9.1e-01 -6.5j,  2.3e+00+11.4j,  1.0e+01 +6.9j],
        [-6.1e+00 +4.5j,  5.1e+00 -0.3j, -8.0e-01 -6.8j],
        [ 1.2e+01-10.7j, -6.8e+00 +2.2j,  6.1e+00+13.6j]],

       [[-8.2e+00 -5.5j, -6.2e+00 -4.5j, -9.8e-01-10.2j],
        [-2.4e+00 -5.2j, -1.1e+00 +0.8j,  4.1e+00 -1.7j],
        [ 1.5e+01 +3.9j,  9.6e+00 -2.6j,  4.0e+00+10.1j],
        [-1.1e+01 -3.j , -2.3e+00+10.1j,  2.6e+00 -2.2j],
        [ 1.8e+01 -0.3j,  5.5e+00 -6.9j,  4.2e+00+10.3j]],

       [[-3.1e+00 -9.5j, -2.3e+00 -8.2j,  5.2e+00 -9.3j],
        [ 1.3e+00 -3.2j,  1.9e+00 -1.8j,  4.2e+00 -0.7j],
        [ 1.4e+01+10.j ,  4.0e+00 +2.1j, -5.1e+00+14.1j],
        [-1.3e+01 -4.2j,  2.5e+00 +8.j ,  6.7e+00 -7.1j],
        [ 1.7e+01+10.5j,  5.7e+00 -1.8j, -4.8e+00+14.2j]],

       [[-6.3e+00 -1.5j,  6.9e+00 +0.j ,  6.3e+00 -7.5j],
        [ 3.0e-04 -4.5j, -1.4e+00 +2.2j,  3.6e+00 +1.7j],
        

# Test with multilinear_product.mat

In [18]:
A = np.load('A.npy')
print('A:')
print(A)

B = np.load('B.npy')
print('B:')
print(B)

C = np.load('C.npy')
print('C:')
print(C)

tenX = np.load('mtenX.npy')
print('Tensor X:')
print(tenX)

tenY = np.load('mtenY.npy')
print('Tensor Y:')
print(tenY)

A:
[[ 1.8  0.9  0.6]
 [-0.4  1.1 -1.5]
 [-1.5  0.2 -0.6]
 [-0.6  0.3 -1.8]]
B:
[[-0.4 -2.2  0.8  0.1]
 [ 0.9  1.7  0.4 -0.8]
 [ 0.7  1.3  0.7  1.4]
 [ 2.3 -0.6 -0.1  0. ]
 [ 0.2  0.2 -0.   0.7]]
C:
[[-0.9 -0.3]
 [-1.1  1.2]
 [-0.1  0.6]]
Tensor X:
[[[ 2.7 -1.1  0.7  1.5]
  [-1.1  1.  -0.3 -2.3]
  [ 0.6  0.3  0.2 -1.6]]

 [[ 0.4 -1.5 -0.7 -0.9]
  [-0.7 -0.9 -0.9  1.3]
  [-0.3 -0.4 -0.4 -1. ]]]
Tensor Y:
[[[-2.1e+00 -1.3e+00  3.2e-01 -9.0e+00  2.6e-01]
  [ 1.3e+00  1.6e+00  8.3e-01  6.6e+00 -8.0e-03]
  [ 2.9e+00  1.6e-01  2.0e+00  9.9e+00  7.4e-01]
  [ 5.5e-01  3.0e+00 -1.4e+00  6.1e+00 -1.1e+00]]

 [[ 6.9e+00 -1.2e+01 -1.2e+01 -7.7e+00 -2.0e+00]
  [ 1.7e+00 -2.0e+00  7.9e+00  6.7e+00  3.3e+00]
  [-1.7e+00  3.3e+00  1.2e+01  8.5e+00  3.7e+00]
  [-2.4e+00  4.8e+00  8.1e+00  6.7e+00  2.0e+00]]

 [[ 3.8e+00 -4.3e+00 -5.1e+00  5.5e-01 -9.3e-01]
  [ 1.6e-01 -1.5e+00  2.9e+00  4.4e-02  1.4e+00]
  [-1.9e+00  1.3e+00  4.3e+00 -6.3e-01  1.3e+00]
  [-1.3e+00  7.3e-01  4.0e+00  2.2e-01  1.3e+00]]]


In [19]:
print('ten_mat_product function:')
print(ten_mat_multiprod(tenX,np.array([C,A,B])))

ten_mat_product function:
[[[-2.1e+00 -1.3e+00  3.2e-01 -9.0e+00  2.6e-01]
  [ 1.3e+00  1.6e+00  8.3e-01  6.6e+00 -8.0e-03]
  [ 2.9e+00  1.6e-01  2.0e+00  9.9e+00  7.4e-01]
  [ 5.5e-01  3.0e+00 -1.4e+00  6.1e+00 -1.1e+00]]

 [[ 6.9e+00 -1.2e+01 -1.2e+01 -7.7e+00 -2.0e+00]
  [ 1.7e+00 -2.0e+00  7.9e+00  6.7e+00  3.3e+00]
  [-1.7e+00  3.3e+00  1.2e+01  8.5e+00  3.7e+00]
  [-2.4e+00  4.8e+00  8.1e+00  6.7e+00  2.0e+00]]

 [[ 3.8e+00 -4.3e+00 -5.1e+00  5.5e-01 -9.3e-01]
  [ 1.6e-01 -1.5e+00  2.9e+00  4.4e-02  1.4e+00]
  [-1.9e+00  1.3e+00  4.3e+00 -6.3e-01  1.3e+00]
  [-1.3e+00  7.3e-01  4.0e+00  2.2e-01  1.3e+00]]]


In [20]:
tl.tenalg.multi_mode_dot(tenX,[C,A,B])

array([[[-2.1e+00, -1.3e+00,  3.2e-01, -9.0e+00,  2.6e-01],
        [ 1.3e+00,  1.6e+00,  8.3e-01,  6.6e+00, -8.0e-03],
        [ 2.9e+00,  1.6e-01,  2.0e+00,  9.9e+00,  7.4e-01],
        [ 5.5e-01,  3.0e+00, -1.4e+00,  6.1e+00, -1.1e+00]],

       [[ 6.9e+00, -1.2e+01, -1.2e+01, -7.7e+00, -2.0e+00],
        [ 1.7e+00, -2.0e+00,  7.9e+00,  6.7e+00,  3.3e+00],
        [-1.7e+00,  3.3e+00,  1.2e+01,  8.5e+00,  3.7e+00],
        [-2.4e+00,  4.8e+00,  8.1e+00,  6.7e+00,  2.0e+00]],

       [[ 3.8e+00, -4.3e+00, -5.1e+00,  5.5e-01, -9.3e-01],
        [ 1.6e-01, -1.5e+00,  2.9e+00,  4.4e-02,  1.4e+00],
        [-1.9e+00,  1.3e+00,  4.3e+00, -6.3e-01,  1.3e+00],
        [-1.3e+00,  7.3e-01,  4.0e+00,  2.2e-01,  1.3e+00]]])

# Test with an example presented in Tensor Decompositions and Applications

In [8]:
print('Tensor X:')
X = np.moveaxis(np.arange(1,25).reshape([2,3,4]),1,2).reshape([2,3,4],order = 'F')
print(X)
print(X.shape)

print('Matrix U:')
U = np.arange(1,7).reshape([2,3],order = 'F')
print(U)

#The mode must match the number of columns in the matrix.

Tensor X:
[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]

 [[13 16 19 22]
  [14 17 20 23]
  [15 18 21 24]]]
(2, 3, 4)
Matrix U:
[[1 3 5]
 [2 4 6]]


In [9]:
Y = ten_mat_prod(X,U,1)
print(Y)

[[[ 22  49  76 103]
  [ 28  64 100 136]]

 [[130 157 184 211]
  [172 208 244 280]]]


## About this notebook

**Author**: Kenneth B. dos A. Benício

**Uptaded on**: 2020-03-30